import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import Annoucement from "@/components/Annoucement/Annoucement";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Annoucement />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
